stages:
  - build
  - deploy

build_job:
  image: gradle:jdk8
  only:
    - main
  stage: build
  script:
    - java -version
    - gradle build jar
    # ---
    - mkdir jMARS_Recorder
    - mv app/build/libs/jMARS_Recorder-*.jar jMARS_Recorder/
    - mv README.md jMARS_Recorder/README.md
    - mv LICENSE.txt jMARS_Recorder/LICENSE.txt
    - tar -zcvf jMARS_Recorder-latest.tgz jMARS_Recorder/
  artifacts:
    paths:
      - jMARS_Recorder-latest.tgz

pages:
  only:
    - main
  stage: deploy
  script:
    - mkdir public
    - mv jMARS_Recorder-latest.tgz public/
  dependencies:
    - build_job
  artifacts:
    paths:
      - public
