image: gradle:jdk17

stages:
  - build

build:
  only:
    refs:
      - main
    variables:
      - $CI_COMMIT_TAG
  stage: build
  script:
    # build
    - java -version
    - gradle jar
    # publish
    - mkdir jMARS_Recorder
    - mv app/build/libs/jMARS_Recorder-*.jar jMARS_Recorder/
    - mv README.md jMARS_Recorder/README.md
    - ls
  artifacts:
    paths:
      - jMARS_Recorder/
