stages:
  - build
  - deploy

build_job:
  image: gradle:jdk17-jammy
  only: 
    - main
  stage: build
  script:
    - java -version
    - gradle jar
    # ---
    - mkdir jMARS_Recorder
    - mv app/build/libs/jMARS_Recorder-*.jar jMARS_Recorder/
    - mv README.md jMARS_Recorder/README.md
    - mv LICENSE.txt jMARS_Recorder/LICENSE.txt
    - apt-get update
    - apt-get install -y zip
    - zip -r jMARS_Recorder-latest.zip jMARS_Recorder/
  artifacts:
    paths:
      - jMARS_Recorder-latest.zip

pages:
  only: 
    - main
  stage: deploy
  script:
    - mkdir public
    - mv jMARS_Recorder-latest.zip public/
  dependencies:
    - build_job
  artifacts:
    paths:
      - public
