stages:
  - build
  - deploy

build_job:
  image: gradle:jdk17
  only: 
    - main
    - tags
  stage: build
  script:
    - java -version
    - gradle jar
    # ---
    - mkdir jMARS_Recorder
    - mv app/build/libs/jMARS_Recorder-*.jar jMARS_Recorder/
    - mv README.md jMARS_Recorder/README.md
    - mv LICENSE.txt jMARS_Recorder/LICENSE.txt
    - tar -zcvf jMARS_Recorder-latest.tar.gz jMARS_Recorder/
  artifacts:
    paths:
      - jMARS_Recorder-latest.tar.gz

pages:
  stage: deploy
  script:
    - mkdir public
    - mv jMARS_Recorder-latest.tar.gz public/
  dependencies:
    - build_job
  artifacts:
    paths:
      - public
